# Generated by Django 6.0.2 on 2026-04-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_module', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='correctionitem',
            name='correction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_module.correction'),
        ),
    ]
