# Generated by Django 6.0.2 on 2026-03-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(editable=False, help_text='Admission Number for students or Staff ID for staff', max_length=50, unique=True),
        ),
    ]
