# Generated by Django 6.0.2 on 2026-03-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
