# Generated by Django 6.0.2 on 2026-04-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationbooking',
            name='meeting_type',
            field=models.CharField(choices=[('in_person', 'In-Person (Boardroom)'), ('video_call', 'Video Call (Zoom/Teams/Google Meet)'), ('hybrid', 'Hybrid (In-person + Virtual)'), ('phone_call', 'Phone Call')], default='in_person', max_length=20),
        ),
    ]
