# Generated by Django 6.0.2 on 2026-04-05 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_presentationbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (Jan-Mar)'), ('Q2', 'Q2 (Apr-Jun)'), ('Q3', 'Q3 (Jul-Sep)'), ('Q4', 'Q4 (Oct-Dec)')], max_length=2)),
                ('year', models.IntegerField()),
                ('work_done', models.TextField()),
                ('progress', models.TextField()),
                ('challenges', models.TextField(blank=True, null=True)),
                ('supervisor_feedback', models.TextField(blank=True, null=True)),
                ('next_plan', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_reports', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'quarter', 'year')},
            },
        ),
    ]
