# Generated by Django 6.0.2 on 2026-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_quarterlyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlyreport',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
