# Generated by Django 6.0.2 on 2026-04-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_quarterlyreport_is_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationbooking',
            name='meeting_type',
            field=models.CharField(choices=[('in_person', 'In-Person'), ('video_call', 'Video Call'), ('phone_call', 'Phone Call')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='presentationbooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
