# Generated by Django 6.0.2 on 2026-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('in_progress', 'In Progress'), ('upcoming', 'Upcoming')], max_length=20),
        ),
    ]
