# Generated by Django 6.0.2 on 2026-03-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_remove_milestone_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
