# Generated by Django 6.0.2 on 2026-04-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('concept_note', 'Concept Note'), ('proposal_draft', 'Proposal Draft'), ('proposal_final', 'Proposal Final'), ('chapter_draft', 'Chapter Draft'), ('chapter_revision', 'Chapter Revision'), ('full_thesis_draft', 'Full Thesis Draft'), ('final_thesis_submission', 'Final Thesis Submission'), ('presentation_slides', 'Presentation Slides'), ('research_paper', 'Research Paper'), ('progress_report', 'Progress Report'), ('dataset_appendices', 'Dataset / Appendices')], default='chapter_draft', max_length=50)),
                ('chapter', models.CharField(blank=True, choices=[('chapter_1', 'Chapter 1: Introduction'), ('chapter_2', 'Chapter 2: Literature Review'), ('chapter_3', 'Chapter 3: Methodology'), ('chapter_4', 'Chapter 4: Data Analysis'), ('chapter_5', 'Chapter 5: Discussion'), ('chapter_6', 'Chapter 6: Conclusion & Recommendations'), ('all_chapters', 'All Chapters'), ('proposal_document', 'Proposal Document'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=50, null=True)),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('pending', 'Pending'), ('revision', 'Needs Revision')], default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('concept_note', 'Concept'), ('proposal', 'Proposal'), ('data_collection', 'Data Collection'), ('thesis', 'Thesis'), ('completed', 'Completed')], default='concept_note', max_length=50)),
            ],
        ),
    ]
