# Generated by Django 6.0.2 on 2026-03-21 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.submission'),
        ),
    ]
