# Generated by Django 6.0.2 on 2026-04-07 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='chair_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('deferred', 'Deferred')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chair_reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
