# Generated by Django 6.0.2 on 2026-04-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_submission_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='chapter',
            field=models.CharField(blank=True, choices=[('chapter_1', 'Chapter 1: Introduction'), ('chapter_2', 'Chapter 2: Literature Review'), ('chapter_3', 'Chapter 3: Methodology'), ('chapter_4', 'Chapter 4: Data Analysis'), ('chapter_5', 'Chapter 5: Discussion'), ('chapter_6', 'Chapter 6: Conclusion & Recommendations'), ('all_chapters', 'All Chapters'), ('proposal_document', 'Proposal Document'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('concept_note', 'Concept Note'), ('proposal_draft', 'Proposal Draft'), ('proposal_final', 'Proposal Final'), ('chapter_draft', 'Chapter Draft'), ('chapter_revision', 'Chapter Revision'), ('full_thesis_draft', 'Full Thesis Draft'), ('final_thesis_submission', 'Final Thesis Submission'), ('presentation_slides', 'Presentation Slides'), ('research_paper', 'Research Paper'), ('progress_report', 'Progress Report'), ('dataset_appendices', 'Dataset / Appendices')], default='chapter_draft', max_length=50),
        ),
    ]
